
# 1. PULL  IN THE LIBRARIES ETC

import numpy as np
import tensorflow as tf



# 2. LOAD THE DATA
# 3. EXPLORE THE DATA (FOLDER STRUCTURE INCLUDED)
# 4. MODEL DEFINITION
# 5. SET UP IMAGE DATA GENERATOR (TRAIN AND VALIDATION)
# 6. IMAGE AUGMENTATION
# 7. DEFINE CALLBACKS
# 8. MODEL COMPILE
# 9. MODEL TRAINING
# 10. PREDICTION